### ISSUE TITLE
How can I document a type declaration?

### ISSUE THREAD

**Issue by avsakharov** [elcorto/sphinx-autodoc#1]
Hello!

I have the following problem. I'm making a type declaration. For example:
```
from typing import Tuple
Type1 = Tuple[str, float]
```
I would like Sphinx to document this declaration like a function declaration. How can I do this? Thanks in advance.

**Comment by elcorto** [comment]
Hi

This question doesn't relate to code in this project, but is rather a Sphinx question.

Nevertheless, since I have no examples in this repo: you can try to use the `sphinx-autodoc-typehints` extension. I used this [here](https://github.com/elcorto/psweep), using jupyterbook which uses sphinx. A config example is [here](https://github.com/elcorto/psweep/blob/master/doc/source/_config.yml#L31). However, I don't know if it handles custom types.
